apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - {{ .Values.mysql.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
